### ISSUE TITLE
DecomposeSum

### ISSUE THREAD

**Issue by MichaelXavier** [patrickt/fastsum#1]
Greetings!

We had talked about a combinator to decompose a sum which could be used in pattern matching. It would remove the head of the type list and return either the matched value or a sum with that type removed. Here's what I've got:

```haskell
-- | Try to extract the first type from the sum. On failure, return a
-- sum that eliminates that as a possibility. This would probably have
-- to be exported by the library so we don't have to export the Sum
-- constructor.
decomposeSum :: Sum (e ': es) b -> Either (Sum es b) (e b)
decomposeSum sum@(Sum n v) = maybe (Left (Sum (n - 1) v)) Right (projectSum sum)


-- | For a sum with precisely one type in the type list, we can safely
-- project that value.
decomposeLast :: Sum '[e] b -> e b
decomposeLast = either (error "impossible") id . decomposeSum
```

Would you accept a PR with these combinators? Also, are there any other tasks I could help with to get this package ready for a hackage release?

**Comment by robrix** [comment]
> Would you accept a PR with these combinators? 

👍 I’m on board with this. In another package I’ve got a function analogous to `decomposeLast` called `strengthenSingleton`, and find it v. handy indeed.

cc @patrickt—I don’t think I’m a collaborator on this repo so can’t label issues etc

**Comment by patrickt** [comment]
Fixed! Thanks, @MichaelXavier.

**Comment by MichaelXavier** [comment]
Heck. I literally just pushed my version! They're basically compatible but mine also adds an example with some kind of cool tech to erase some of the type parameter that aren't needed when you're simply unioning across `*`-kinded values. I'd like to see what you all think so I'll send that as a PR.
