### ISSUE TITLE
Build fails with ghc-8.6.4 internal error

### ISSUE THREAD

**Issue by marcelosousa** [patrickt/fastsum#11]
When trying to build the package with cabal, I encounter the following error:

```
Resolving dependencies...
Configuring fastsum-0.1.1.0...
Preprocessing library for fastsum-0.1.1.0..
Building library for fastsum-0.1.1.0..
[1 of 2] Compiling Data.Sum.Templates ( src/Data/Sum/Templates.hs, dist/build/Data/Sum/Templates.o )
[2 of 2] Compiling Data.Sum         ( src/Data/Sum.hs, dist/build/Data/Sum.o )
ghc: internal error: Unable to commit 1048576 bytes of memory
    (GHC version 8.6.4 for x86_64_unknown_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Failed to install fastsum-0.1.1.0
cabal: Error: some packages failed to install:
fastsum-0.1.1.0-GQUPDK7HNQ3BzBCRuqjYJ7 failed during the building phase. The
exception was:
ExitFailure (-6)
```

I'm using:
```
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```

This seems to be a memory problem and I observe the 4GB of the memory on the VM are consumed by the `ghc` process before the failure.

Any help solving this issue would be great.

**Comment by robrix** [comment]
Sorry this slipped through the cracks!

IIRC, you can pass RTS flags to `ghc` itself, upping its heap allotment, using `--ghc-options`, something like `--ghc-options="+RTS … -RTS"`. Unfortunately, I’m not sure which, if any, of the various RTS options (cf the ghc user‘s guide, starting around [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#miscellaneous-rts-options)) would really help here.

A little digging suggests that this might be a `ghc` bug: https://gitlab.haskell.org/ghc/ghc/issues/16613

It’s not super surprising that the `fastsum` build would trigger this given the number of instances, &c., that we’re asking it to compile. Ultimately, I’m not sure that there’s anything we can do about it 😞

**Comment by patrickt** [comment]
Yeah, I don't think there's anything we can do about this: `fastsum` stretches GHC to its limits, and 4GB of memory may simply not be enough for the instances we need to declare. If this is in some sort of container, I recommend allocating more RAM or more swap for it. Beyond that, there's little we can do, so I'm going to close this.
